const animateTypeList = [
  "simpleFade",
  "scrollTop",
  "scrollLeft",
  "scrollBottom",
  "scrollRight",
  "curtainTopLeft",
  "curtainTopRight",
  "curtainBottomLeft",
  "curtainBottomRight",
  "curtainSliceLeft",
  "curtainSliceRight",
  "blindCurtainTopLeft",
  "blindCurtainTopRight",
  "blindCurtainBottomLeft",
  "blindCurtainBottomRight",
  "blindCurtainSliceTop",
  "blindCurtainSliceBottom",
  "mosaic",
  "mosaicReverse",
  "mosaicRandom",
  "mosaicSpiral",
  "mosaicSpiralReverse",
  "topLeftBottomRight",
  "bottomRightTopLeft",
  "bottomLeftTopRight",
  "topRightBottomLeft",
  "stampede",
  "rotateYLeft",
  "rotateYRight",
  "rotateXTop",
  "rotateXBottom"
];

export default animateTypeList;
